apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator-controller
  namespace: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: spark-operator
      app.kubernetes.io/name: spark-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: spark-operator
        app.kubernetes.io/name: spark-operator
    spec:
      containers:
      - name: spark-operator-controller
        image: ghcr.io/kubeflow/spark-operator/controller:2.2.1
        args:
        - controller
        - start
        - --zap-log-level=info
        - --namespaces=default
        - --controller-threads=10
        - --enable-ui-service=true
        - --enable-metrics=true
        - --metrics-bind-address=:8080
        - --metrics-endpoint=/metrics
        - --leader-election=true
        - --leader-election-lock-name=spark-operator-controller-lock
        - --leader-election-lock-namespace=spark-operator
        - --submitter-type=grpc
        - --grpc-server-address=localhost:50051
        - --grpc-submit-timeout=10s
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      
      # Native Submit Plugin Sidecar
      - name: native-submit
        image: your-registry/native-submit:latest
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        - containerPort: 9090
          name: health
          protocol: TCP
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: HEALTH_PORT
          value: "9090"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 185
          runAsGroup: 185
          seccompProfile:
            type: RuntimeDefault
      
      volumes:
      - emptyDir:
          sizeLimit: 1Gi
        name: tmp
      securityContext:
        fsGroup: 185
      serviceAccountName: spark-operator-controller 